### ISSUE TITLE
Mapping chart of accounts with carbon factors

### ISSUE THREAD

**Issue by BonnetAdam** [MyCityCO2/co2-switzerland#6]
[mapping_coa_carbon.csv](https://github.com/MyCityCO2/co2-switzerland/files/14605928/mapping_coa_carbon.csv)

**Comment by ben3474** [comment]
There you go
[ch_map_emission_factors_vs_chart_of_accounts.xlsx](https://github.com/MyCityCO2/co2-switzerland/files/14607060/ch_map_emission_factors_vs_chart_of_accounts.xlsx)

**Comment by ben3474** [comment]
Still need to provide a more accurate mapping but good enough to test

**Comment by ben3474** [comment]
There is a first version of the file
[ch_map_emission_factors_vs_chart_of_accounts.xlsx](https://github.com/MyCityCO2/co2-switzerland/files/14607086/ch_map_emission_factors_vs_chart_of_accounts.xlsx)

**Comment by ben3474** [comment]
Here's a first version of the file
[ch_map_emission_factors_vs_chart_of_accounts.xlsx](https://github.com/MyCityCO2/co2-switzerland/files/14607096/ch_map_emission_factors_vs_chart_of_accounts.xlsx)

**Comment by ben3474** [comment]
Final version
[ch_map_emission_factors_vs_chart_of_accounts.xlsx](https://github.com/MyCityCO2/co2-switzerland/files/14607575/ch_map_emission_factors_vs_chart_of_accounts.xlsx)
