### ISSUE TITLE
Mapping chart of accounts with categories

### ISSUE THREAD

**Issue by BonnetAdam** [MyCityCO2/co2-switzerland#7]
[coa_condition.csv](https://github.com/MyCityCO2/co2-switzerland/files/14605943/coa_condition.csv)

**Comment by ben3474** [comment]
There's a first version to be tested
[ch_map_chart_of_account_vs_category.csv](https://github.com/MyCityCO2/co2-switzerland/files/14607264/ch_map_chart_of_account_vs_category.csv)

**Comment by ben3474** [comment]
[ch_map_chart_of_account_vs_category.csv](https://github.com/MyCityCO2/co2-switzerland/files/14608783/ch_map_chart_of_account_vs_category.csv)

**Comment by ben3474** [comment]
[ch_map_chart_of_account_vs_category.csv](https://github.com/MyCityCO2/co2-switzerland/files/14609059/ch_map_chart_of_account_vs_category.csv)
