### ISSUE TITLE
Provide MCH2 aggr

### ISSUE THREAD

**Issue by BonnetAdam** [MyCityCO2/co2-switzerland#8]

**Comment by ben3474** [comment]
Taken from this data source https://www.vd.ch/themes/etat-droit-finances/communes/finances-communales/mch2/manuel-et-plan-comptable and only defining spendings (investments and regular).
This is the aggregated MCH2 swiss chart of account and not the detailed one as we don't have the data yet to do so.
[ch_ref_chart_of_accounts.xlsx](https://github.com/MyCityCO2/co2-switzerland/files/14606481/ch_ref_chart_of_accounts.xlsx)
