### ISSUE TITLE
Account asset mapping <-> carbon factor 

### ISSUE THREAD

**Issue by BonnetAdam** [MyCityCO2/co2-switzerland#9]
[account_asset_mapping.csv](https://github.com/MyCityCO2/co2-switzerland/files/14605974/account_asset_mapping.csv)

**Comment by ben3474** [comment]
Here's a first version good enough to be tested
[account_asset_mapping.csv](https://github.com/MyCityCO2/co2-switzerland/files/14607121/account_asset_mapping.csv)

**Comment by ben3474** [comment]
[account_asset_mapping.csv](https://github.com/MyCityCO2/co2-switzerland/files/14608684/account_asset_mapping.csv)
